Custom disaster-based train/test splits for xView2 dataset
torchgeo/torchgeo pull request #2416
Opened 2024-11-18 16:12 UTC by burakekim

cc: @calebrob6 

`XView2DistShift` is a subclass of `XView2` designed to modify the original train/test splits. Similar to EuroSATSpatial #2074, this class enables domain adaptation and out-of-distribution (OOD) detection experiments.

From the docstring: 
> This class allows for the selection of particular disasters to be used as the training set (in-domain) and test set (out-of-domain). The dataset can be split according to the disaster names specified by the user, enabling the model to train on one disaster type and evaluate on a different, out-of-domain disaster. The goal is to test the generalization ability of models trained on one disaster to perform on another.

TODO: test coverage

2024-11-18 19:35 UTC, adamjstewart commented
We decided on EuroSAT _Spatial_ before, why switch to XView2 _Dist Shift_ now? Will there be any corresponding citations for these new splits?

It would be nice to move more of the shared code in the XView2 base class so that the only thing that needs to be changed in this subclass is the URLs. How different are these datasets?

2024-11-18 20:29 UTC, burakekim commented
> We decided on EuroSAT _Spatial_ before, why switch to XView2 _Dist Shift_ now?

EuroSAT split

2025-02-01 15:42 UTC, calebrob6 commented
Great dataset. highly recommend

2025-02-01 20:08 UTC, burakekim commented
This is how it works: 

```root = "/data/dataood/xview2"

id_ood_disaster =  [{'disaster_name': 'hurricane-matthew', 'pre-post': 'post'},
  {'disaster_name': 'mexico-earthquake', 'pre-post': 'post'}]

xview2 = XView2DistShift(root=root, 
                         split="test",
                         id_ood_disaster=id_ood_disaster)

> ID sample len: 311, OOD sample len: 159
```

All the existing methods are revised to make XView2DistShift work as it should. I cannot seem to find a way to prune further (unless I upstream a method or two to `XView2` but that is too much of refactoring).

If it looks good, I can go ahead with unit tests. 

@adamjstewart, just to loop you in: As you may have noticed, we are upstreaming some modifications to existing datasets to make them suitable for assessing models under controlled domain shifts. This unlocks a whole new research dimension in TG that users can easily explore, including but not limited to robustness, generalization ability, anomaly detection, and novelty detection!

2025-04-19 21:01 UTC, burakekim commented
@adamjstewart is this good to go?

2025-04-20 12:29 UTC, adamjstewart requested changes

2025-04-20 12:29 UTC, adamjstewart commented on .gitignore
> +xbdood.ipynb
What is this?

2025-04-20 12:29 UTC, adamjstewart commented on torchgeo/datasets/xview.py
> +        split: str = 'train',
Not required, but I'm trying to convert more of our datasets to use proper type hints:
```suggestion
        split: Literal['train', 'test'] = 'train',
```
Where `Literal` is from `typing`. Not all str are valid, only these two.

2025-04-20 12:29 UTC, adamjstewart commented on torchgeo/datasets/xview.py
> +        transforms: Callable[[dict[str, torch.Tensor]], dict[str, torch.Tensor]]
```suggestion
        transforms: Callable[[dict[str, Tensor]], dict[str, Tensor]]
```

2025-04-20 12:29 UTC, adamjstewart commented on torchgeo/datasets/xview.py
> +        id_ood_disaster: list[dict[str, str]] = [
Do tuples or other Sequences also work?

2025-04-20 12:29 UTC, adamjstewart commented on torchgeo/datasets/xview.py
> +            ValueError: If a disaster name in `id_ood_disaster` is not one of the valid disasters.
```suggestion
            ValueError: If a disaster name in *id_ood_disaster* is not one of the valid disasters.
```
Same formatting, but makes it more clear that it's in italics, not teletype.

2025-04-20 12:29 UTC, adamjstewart commented on torchgeo/datasets/xview.py
> +        """Get an item from the dataset at the given index."""
Need to document Args and Returns

2025-04-20 12:29 UTC, adamjstewart commented on torchgeo/datasets/xview.py
> +        """Return the total number of samples in the dataset."""
Need to document Returns

2025-04-20 12:29 UTC, adamjstewart commented on torchgeo/datasets/xview.py
> +            images = glob.glob(os.path.join(image_root, '*.png'))
These should be sorted in order to ensure reproducibility

2025-04-20 12:29 UTC, adamjstewart commented on torchgeo/datasets/xview.py
> +        """Return the filepaths for the train (ID) and test (OOD) sets based on disaster name and pre-post disaster type.
Some of these lines look longer than 88 chars

2025-04-20 12:29 UTC, adamjstewart commented on torchgeo/datasets/xview.py
> +        )
This is rather complicated. Do we need to store metadata for both train and test when only one is chosen?

2025-04-20 12:29 UTC, adamjstewart commented on torchgeo/datasets/xview.py
> +    on others.
Needs:
```rst
.. versionadded:: 0.8
```

2025-04-20 13:17 UTC, burakekim commented on .gitignore
> +xbdood.ipynb
That is for me to sanity check -- not here to stay

2025-04-20 13:18 UTC, burakekim commented on torchgeo/datasets/xview.py
> +        split: str = 'train',
Liked it! Will use this

2025-04-20 13:49 UTC, burakekim commented on torchgeo/datasets/xview.py
> +        id_ood_disaster: list[dict[str, str]] = [
No. Currently we support lists only

2025-04-20 13:54 UTC, burakekim commented
Better now. Thanks for the review @adamjstewart!

2025-04-23 15:35 UTC, calebrob6 commented on torchgeo/datasets/xview.py
> +        )
why not?
```
return len(self.split_files[self.split])
```

2025-04-23 15:35 UTC, calebrob6 commented on torchgeo/datasets/xview.py
> +        file_info = (
Same here -- does `self.split_files[self.split][index]` work?

2025-04-23 20:49 UTC, burakekim commented on torchgeo/datasets/xview.py
> +        )
This works! Thanks

2025-04-23 20:49 UTC, burakekim commented on torchgeo/datasets/xview.py
> +        file_info = (
Works -- thanks!

2025-04-30 17:29 UTC, adamjstewart requested changes

2025-04-30 17:29 UTC, adamjstewart commented on .gitignore
> +.pyre/
Can you undo changes to this file? You removed an EOL char.

2025-04-30 17:29 UTC, adamjstewart commented on torchgeo/datasets/xview.py
> +    ]
```suggestion
    valid_disasters = (
        'hurricane-harvey',
        'socal-fire',
        'hurricane-matthew',
        'mexico-earthquake',
        'guatemala-volcano',
        'santa-rosa-wildfire',
        'palu-tsunami',
        'hurricane-florence',
        'hurricane-michael',
        'midwest-flooding',
    )
```

2025-04-30 17:30 UTC, adamjstewart commented on torchgeo/datasets/xview.py
> +        id_ood_disaster: list[dict[str, str]] = [
I don't see anything in the code that suggests that a tuple wouldn't work. If both a tuple and list are valid, I would use `Sequence` for the type hints and tuple for the default value.

2025-05-11 09:25 UTC, adamjstewart requested changes
Still a lot of concerns about how id/ood arguments are handled.

2025-05-11 09:25 UTC, adamjstewart commented on tests/datasets/test_xview.py
> +        monkeypatch.setattr(
Might not even need to monkeypatch this if you remove `checksum=True`, I never bother with this

2025-05-11 09:25 UTC, adamjstewart commented on tests/datasets/test_xview.py
> +                {'disaster_name': 'hurricane-harvey', 'pre-post': 'post'},
Is this duplication required for some reason?

2025-05-11 09:25 UTC, adamjstewart commented on tests/datasets/test_xview.py
> +        assert len(dataset) > 0
Let's test a specific length to ensure it behaves as expected. Can use an if-statement if it's different for train and test.

2025-05-11 09:25 UTC, adamjstewart commented on tests/datasets/test_xview.py
> +                root='tests/data/xview2',
```suggestion
                root=os.path.join('tests', 'data', 'xview2'),
```
Windows

2025-05-11 09:25 UTC, adamjstewart commented on torchgeo/datasets/xview.py
> +            id_ood_disaster: List containing in-distribution and out-of-distribution disaster names.
Needs more description. Clarify that both `disaster_name` and `pre-post` are required. Also explain what they mean, I have no idea

2025-05-11 09:25 UTC, adamjstewart commented on torchgeo/datasets/xview.py
> +            if 'disaster_name' not in disaster:
This check is duplicated below...

2025-05-11 09:25 UTC, adamjstewart commented on torchgeo/datasets/xview.py
> +            ValueError: If a disaster name in *id_ood_disaster* is not one of the valid disasters.
Seems like many other undocumented cases where these are raised

2025-05-11 09:25 UTC, adamjstewart commented on torchgeo/datasets/xview.py
> +                self.all_files, id_ood_disaster[0], id_ood_disaster[1]
If I pass in a dict of length 100, are the later 98 arguments ignored? Seems like a dict is a bad choice for this. Why not use 4 different parameters so they can be more clearly documented and type checked?

2026-05-11 20:17 UTC, calebrob6 commented
@adamjstewart I think this one would be great to have and isn't a large lift. I'm going to take it over.

2026-07-09 15:10 UTC, closed without merging