Point geo data sampler
torchgeo/torchgeo pull request #800
Opened 2022-09-28 20:07 UTC by ak3ra

This PR attempts to implement a PointGeo Sampler. 
The `PointGeoSampler` takes in an Image dataset and a dataset containing (lat/lon) points (eg GBIF, INaturalist), finds the intersection of the two datasets and returns a sample bounding box of the image dataset which contains the lat/lon coordinates.

2022-09-28 20:45 UTC, isaaccorley commented
@ak3ra Thanks for the contribution! Here's a [link](https://torchgeo.readthedocs.io/en/stable/user/contributing.html) to the contributing docs which can give some guidance for fixing the failing github actions. You'll need to run `black` and `isort` from the root of the repo. Then you'll need to run `flake8` and `pydocstyle` and fix any errors that pop up.

2022-09-28 22:07 UTC, adamjstewart commented
@ak3ra I might find some time to work on this this week. Do you mind if I push commits directly to your PR branch?

2022-09-28 22:13 UTC, ak3ra commented
Thanks @isaaccorley I will follow the guidelines !

@adamjstewart, I don't mind at all. Looking forward to having this feature :)

2022-09-29 15:03 UTC, adamjstewart requested changes
@ak3ra and I met over zoom, discussed some of these changes.

I may have changed my mind on the best way to design this halfway through reviewing, get through the end before making too many changes lol. Let me know if any of this isn't clear. I'll let you keep hacking on this for a while and I'm happy to step in and try implementing things myself if you want.

Once we get this working properly, we can worry about testing and code style.

2022-10-10 18:16 UTC, adamjstewart commented
I got buried in prelim and conference prep, so I also haven't gotten a chance to work on this.

2024-08-21 08:21 UTC, adamjstewart commented
@ak3ra is this PR still a work in progress? Not sure if it's still relevant to your research or not.

2025-07-28 20:40 UTC, ivanhigueram commented
There are any updates on this? I am happy to give it a try if it's still in the package's TODO's.

2025-07-28 20:52 UTC, ak3ra commented
Just seeing this two years later, I got busy with other things but I think this would still be super relevant if it hasn't been ported into torchgeo by now. I eventually ended up using a custom sampler for this task and I dont think its 1:1 compatible with torchgeo @ivanhigueram

2025-07-28 21:07 UTC, ivanhigueram commented
Yeah, I completely agree on its relevance. I am currently using the intersection abilities for a custom fine-tuning combining images with point labels. I will try to use what `torchgeo` has to offer, but would be happy to work on this if its useful for the library.

2025-07-28 21:09 UTC, isaaccorley commented
Note that TorchGeo has recently transitioned to using geopandas as a backend so performing spatial intersection with points should be easier to implement now.

2025-07-28 21:19 UTC, ivanhigueram commented
Thanks for your reply @isaaccorley. Is this true for the `0.8` version only or is the current `0.7.1` is still using the index, or am I completely wrong?

2025-07-28 21:40 UTC, isaaccorley commented
It's in the main branch for a future 0.8+ release (we may skip directly to 1.0 for this change though). Any new PointSampler would need to be released in 0.8+ though so it can take advantage of geopandas functions.

2025-07-28 21:43 UTC, ivanhigueram commented
you guys have a timeline for release of the `v1.0`?

2025-07-28 21:46 UTC, adamjstewart commented
I expect a release candidate within 2 months, but it's tricky to say exactly. We try to stick to a 6 month release schedule for new features, but 1.0 is a big change and may require additional testing.

2026-05-11 20:18 UTC, calebrob6 commented
@adamjstewart given that you are refactoring all samplers, I'm going to suggest we close this and move to an issue

2026-05-11 20:24 UTC, closed without merging